# Learn more about configuring your order status UI extension:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-01"

[[extensions]]
name = "wheel-of-fortune"
handle = "wheel-of-fortune"
type = "ui_extension"
uid = "89cd27ee-c299-c5c0-bbfd-027a008a834ca6d6a929"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/extension-targets-overview

[[extensions.targeting]]
module = "./src/OrderStatus.jsx"
target = "purchase.thank-you.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#network-access
network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/latest/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

[extensions.settings]
[[extensions.settings.fields]]
key = "win_probability"
type = "single_line_text_field"
name = "Win chance"
description = "Chance of winning expressed as a percentage (e.g. 30 for 30%). Values between 0-1 are treated as ratios."
default = "30"

[[extensions.settings.fields]]
key = "spin_button_label"
type = "single_line_text_field"
name = "Spin button label"
default = "Spin the Zardo Wheel"

[[extensions.settings.fields]]
key = "winning_message"
type = "single_line_text_field"
name = "Winning message"
default = "Congratulations! You won a mystery gift."

[[extensions.settings.fields]]
key = "consolation_message"
type = "single_line_text_field"
name = "Consolation message"
default = "Better luck next time!"

[[extensions.settings.fields]]
key = "discount_code"
type = "single_line_text_field"
name = "Optional discount code"
description = "If provided, the code is shown when the customer wins."
